spring:
  application:
    name: App
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}"
  cloud:
    config:
      username: admin
      password: secret
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

application:
  prop: 'prod'
