spring:
  application:
    name: App
  config:
    import: "configtree:/etc/config/"
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh # Añade 'refresh' aquí
  endpoint:
    health:
      show-details: always

application:
  prop: 'stage'