spring:
  application:
    name: App
  config:
    import: "file:/etc/config/secrets.yml"
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh # Añade 'refresh' aquí
  endpoint:
    health:
      show-details: always

application:
  prop: 'stage'