server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server

  security:
    user:
      name: ${CONFIG_SERVER_USER:admin}
      password: ${CONFIG_SERVER_PASSWORD:secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
