name: CI/CD Maven - App
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Ejecutar en modo prueba (no escalar realmente)'
        required: false
        default: 'false'


jobs:
  scale-down:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Check Usage and Scale to Zero
        env:
          NORTHFLANK_API_KEY: ${{ secrets.NORTHFLANK_API_KEY }}
          NF_PROJECT_ID: ${{ vars.NF_PROJECT_ID }}
          DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}
        shell: python
        run: |
          import os
          import sys
          import requests
          import json
          import time

          HEADERS = {
            "Authorization": f"Bearer ${{ secrets.NORTHFLANK_API_KEY }}",
            "Content-Type": "application/json"
          }

          resp = requests.get(
            f"https://api.northflank.com/v1/projects/Japp/services/deployment-service",
            headers=HEADERS
          )
          resp.raise_for_status()
          url = resp.json().get("data").get("ports")[0].get("dns")
          print(f"⚠️ URL: {url}")
          refresh_url = f"https://{url}/actuator/refresh"
          refresh_resp = requests.post(refresh_url)
          print(f"Respuesta /actuator/refresh: {refresh_resp.status_code} - {refresh_resp.text}")




