name: Deploy App Configuration
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Ejecutar en modo prueba (no escalar realmente)'
        required: false
        default: 'false'
  push:
    branches:
      - main
    paths:
      - app/config
jobs:
  scale-down:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Requests
        run: |
          pip install requests

      - name: Call /refresh service
        env:
          DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}
        shell: python
        run: |
          import os
          import sys
          import requests
          import json
          import time

          HEADERS = {
            "Authorization": f"Bearer ${{ secrets.NORTHFLANK_API_KEY }}",
            "Content-Type": "application/json"
          }

          resp = requests.get(
            f"https://api.northflank.com/v1/projects/${{ vars.NORTHFLANK_PROJECT_ID }}/services/${{ vars.NORTHFLANK_SERVICE_ID }}",
            headers=HEADERS
          )
          resp.raise_for_status()
          url = resp.json().get("data").get("ports")[0].get("dns")
          print(f" Service URL: {url}")
          refresh_url = f"https://{url}/actuator/refresh"
          refresh_resp = requests.post(refresh_url)
          print(f"Respuesta /actuator/refresh: {refresh_resp.status_code} - {refresh_resp.text}")

