name: Add comment
on: push
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: getterInfo
        id: getter
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          echo "github.ref": "${{github.ref}}"
          echo "github.sha": "${{github.sha}}"
          echo "github.repository": "${{github.repository}}"
          echo "github.event.after": "${{github.event.after}}" 
          echo "github.event.before": "${{github.event.before}}"
          echo "github.event.compare": "${{github.event.compare}}"
          echo "github.event.created": "${{github.event.created}}"
          echo "github.event.deleted": "${{github.event.deleted}}"
          echo "github.event.forced": "${{github.event.forced}}"
          echo "github.event.ref": "${{github.event.ref}}"
          echo "github.actor": "${{github.actor}}
          echo "github.triggering_actor": "${{github.triggering_actor}}
          echo "github.repository_owner": "${{github.repository_owner}}
          echo "github.workspace": "${{github.workspace}}
          
          echo "ref=${{github.ref}}" >> $GITHUB_OUTPUT
          echo "after=${{github.event.after}}" >> $GITHUB_OUTPUT
          echo "before=${{github.event.before}}" >> $GITHUB_OUTPUT
      - name: comparatorInfo
        run: |
          echo "after > before": "${{steps.getter.outputs.after > steps.getter.outputs.before}}"
          echo "rama contiene: 'feature'": ${{ contains(steps.getter.outputs.ref, 'feature') }}
          echo "ref empieza con 'refs/heads/'": ${{ startsWith(steps.getter.outputs.ref, 'refs/heads/') }}
          echo "ref endsWith con '/main'": ${{ endsWith(steps.getter.outputs.ref, '/main') }}
          echo "version": ${{ format('Version: {0}.{1}', '1', '2') }}
